/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import glb from "./tray.glb";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
  };
  materials: {};
};

export function TrayMesh({
  children,
  ...props
}: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(glb) as unknown as GLTFResult;
  return (
    <group {...props} scale={0.1} dispose={null}>
      {/* Align mesh so that the tray bottom is at [0, 0, 0] */}
      <mesh geometry={nodes.Cube.geometry} position={[0, -0.33, 0]}>
        {children}
      </mesh>
    </group>
  );
}

useGLTF.preload(glb);
