/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import glb from "./d12.glb";

type GLTFResult = GLTF & {
  nodes: {
    d12: THREE.Mesh;
  };
  materials: {};
};

export const D12 = React.forwardRef<
  THREE.Group,
  JSX.IntrinsicElements["group"]
>(({ children, ...props }, ref) => {
  const { nodes } = useGLTF(glb) as unknown as GLTFResult;
  return (
    <group ref={ref} {...props} scale={0.1} dispose={null}>
      <group name="dice">
        <mesh name="d12" castShadow receiveShadow geometry={nodes.d12.geometry}>
          {children}
          <group
            name="012_locator_1"
            position={[0, -0.93, 0]}
            rotation={[0, 0, Math.PI]}
          />
          <group
            name="012_locator_10"
            position={[0.68, -0.41, -0.48]}
            rotation={[-1.86, 0.37, -0.89]}
          />
          <group
            name="012_locator_11"
            position={[0.27, 0.44, 0.79]}
            rotation={[1.13, 0.13, -0.28]}
          />
          <group name="012_locator_12" position={[0, 0.96, 0]} />
          <group
            name="012_locator_2"
            position={[-0.25, -0.41, -0.8]}
            rotation={[-2.01, -0.14, 0.28]}
          />
          <group
            name="012_locator_3"
            position={[-0.67, 0.44, 0.5]}
            rotation={[1.29, -0.37, 0.89]}
          />
          <group
            name="012_locator_4"
            position={[-0.84, -0.41, -0.01]}
            rotation={[-1.57, -0.46, 1.57]}
          />
          <group
            name="012_locator_5"
            position={[0.67, -0.41, 0.5]}
            rotation={[-1.29, 0.37, -2.25]}
          />
          <group
            name="012_locator_6"
            position={[-0.27, -0.41, 0.79]}
            rotation={[-1.13, -0.13, 2.86]}
          />
          <group
            name="012_locator_7"
            position={[0.25, 0.44, -0.8]}
            rotation={[2.01, 0.14, -2.86]}
          />
          <group
            name="012_locator_8"
            position={[-0.68, 0.44, -0.48]}
            rotation={[1.86, -0.37, 2.25]}
          />
          <group
            name="012_locator_9"
            position={[0.84, 0.44, -0.01]}
            rotation={[1.57, 0.46, -1.57]}
          />
        </mesh>
      </group>
    </group>
  );
});

useGLTF.preload(glb);
